version: "3.9"
services:
    db:
        build: ./db
        command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8 --collation-server=utf8_unicode_ci
        restart: unless-stopped
        expose:
            - 3306
        environment:
            # These password and stuff is not neccesarry too secret
            MYSQL_ROOT_PASSWORD: 123
            MYSQL_USER: user
            # - MYSQL_PASSWORD=db_password
            MYSQL_DATABASE: server2
            MYSQL_PASSWORD: 123456

    server:
        build: ./server
        restart: unless-stopped
        ports:
            - 8000:8000
        volumes:
            - ./server:/var/www/html
        depends_on:
            - db
