FROM php:8.2-apache

RUN a2enmod rewrite
RUN apt-get update -y && apt-get install -y openssl zip unzip git
RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
RUN docker-php-ext-install mysqli pdo pdo_mysql
WORKDIR /var/www/html/
COPY . .
# config permission
RUN composer install
# RUN php artisan migrate
RUN chown -R root:www-data /var/www/html	
RUN chmod 750 /var/www/html
RUN find . -type f -exec chmod 640 {} \;
RUN find . -type d -exec chmod 750 {} \;

RUN chmod +t -R /var/www/html/


CMD php artisan serve --host=0.0.0.0 --port=8000

EXPOSE 8000