version: "3.9"
services:
    db:
        build: ./db
        command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8 --collation-server=utf8_unicode_ci
        restart: unless-stopped
        expose:
            - 3306
        environment:
            # These password and stuff is not neccesarry too secret
            MYSQL_ROOT_PASSWORD: root
            MYSQL_USER: student_management
            # - MYSQL_PASSWORD=db_password
            MYSQL_DATABASE: student_management
            MYSQL_PASSWORD: 123456

    student_management:
        build: ./student_management
        restart: unless-stopped
        ports:
            - 8000:8000
        volumes:
            - ./student_management/student_management:/var/www/html
        depends_on:
            - db
